name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.40.0

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.3.1"
          enable-cache: true

      - name: Install dependencies
        run: task init

      - name: Run build stage
        run: task build
